// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaPh94fehvgxTUkE0RyBB2-wkhoqo3IhE',
    appId: '1:555320912880:web:a99097775123147b9b0b35',
    messagingSenderId: '555320912880',
    projectId: 'm2miage-a23ea',
    authDomain: 'm2miage-a23ea.firebaseapp.com',
    storageBucket: 'm2miage-a23ea.appspot.com',
    measurementId: 'G-WSZG2GNXEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrN4-pQbEpbPGHg3A5Zw0oR3cKon3xIWk',
    appId: '1:555320912880:android:81fb5b321b1b6b3c9b0b35',
    messagingSenderId: '555320912880',
    projectId: 'm2miage-a23ea',
    storageBucket: 'm2miage-a23ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbTAAK3WhXaYZBcvz6MAX2siFbk_L3OQ',
    appId: '1:555320912880:ios:6dde57f0a774d9a39b0b35',
    messagingSenderId: '555320912880',
    projectId: 'm2miage-a23ea',
    storageBucket: 'm2miage-a23ea.appspot.com',
    iosClientId: '555320912880-1ck4k507hhm0pon1gbtlfgtr6ie7k3e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbTAAK3WhXaYZBcvz6MAX2siFbk_L3OQ',
    appId: '1:555320912880:ios:6dde57f0a774d9a39b0b35',
    messagingSenderId: '555320912880',
    projectId: 'm2miage-a23ea',
    storageBucket: 'm2miage-a23ea.appspot.com',
    iosClientId: '555320912880-1ck4k507hhm0pon1gbtlfgtr6ie7k3e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinted',
  );
}
